import type { User } from "./types";

// Mock data based on the provided JSON structure
const mockUsers: User[] = [
  {
    id: 1,
    firstName: "Emily",
    lastName: "Johnson",
    maidenName: "Smith",
    age: 28,
    gender: "female",
    email: "emily.johnson@x.dummyjson.com",
    phone: "+81 965-431-3024",
    username: "emilys",
    password: "emilyspass",
    birthDate: "1996-5-30",
    image: "/placeholder.svg?height=200&width=200",
    bloodGroup: "O-",
    height: 193.24,
    weight: 63.16,
    eyeColor: "Green",
    hair: {
      color: "Brown",
      type: "Curly",
    },
    ip: "42.48.100.32",
    address: {
      address: "626 Main Street",
      city: "Phoenix",
      state: "Mississippi",
      stateCode: "MS",
      postalCode: "29112",
      coordinates: {
        lat: -77.16213,
        lng: -92.084824,
      },
      country: "United States",
    },
    macAddress: "47:fa:41:18:ec:eb",
    university: "University of Wisconsin--Madison",
    bank: {
      cardExpire: "03/26",
      cardNumber: "9289760655481815",
      cardType: "Elo",
      currency: "CNY",
      iban: "YPUXISOBI7TTHPK2BR3HAIXL",
    },
    company: {
      department: "Engineering",
      name: "Dooley, Kozey and Cronin",
      title: "Sales Manager",
      address: {
        address: "263 Tenth Street",
        city: "San Francisco",
        state: "Wisconsin",
        stateCode: "WI",
        postalCode: "37657",
        coordinates: {
          lat: 71.814525,
          lng: -161.150263,
        },
        country: "United States",
      },
    },
    ein: "977-175",
    ssn: "900-590-289",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
    crypto: {
      coin: "Bitcoin",
      wallet: "0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a",
      network: "Ethereum (ERC20)",
    },
    role: "admin",
  },
  {
    id: 2,
    firstName: "Michael",
    lastName: "Williams",
    maidenName: "Davis",
    age: 35,
    gender: "male",
    email: "michael.williams@x.dummyjson.com",
    phone: "+1 555-123-4567",
    username: "michaelw",
    password: "michaelpass",
    birthDate: "1989-8-12",
    image: "/placeholder.svg?height=200&width=200",
    bloodGroup: "A+",
    height: 180.5,
    weight: 75.2,
    eyeColor: "Blue",
    hair: {
      color: "Black",
      type: "Straight",
    },
    ip: "192.168.1.1",
    address: {
      address: "123 Oak Street",
      city: "New York",
      state: "New York",
      stateCode: "NY",
      postalCode: "10001",
      coordinates: {
        lat: 40.7128,
        lng: -74.006,
      },
      country: "United States",
    },
    macAddress: "00:1A:2B:3C:4D:5E",
    university: "Columbia University",
    bank: {
      cardExpire: "05/25",
      cardNumber: "4111111111111111",
      cardType: "Visa",
      currency: "USD",
      iban: "US12345678901234567890",
    },
    company: {
      department: "Marketing",
      name: "Global Innovations Inc.",
      title: "Marketing Director",
      address: {
        address: "456 Business Ave",
        city: "New York",
        state: "New York",
        stateCode: "NY",
        postalCode: "10002",
        coordinates: {
          lat: 40.7129,
          lng: -74.007,
        },
        country: "United States",
      },
    },
    ein: "123-456",
    ssn: "123-45-6789",
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
    crypto: {
      coin: "Ethereum",
      wallet: "0x1234567890abcdef1234567890abcdef12345678",
      network: "Ethereum (ERC20)",
    },
    role: "moderator",
  },
  {
    id: 3,
    firstName: "Sarah",
    lastName: "Brown",
    maidenName: "Taylor",
    age: 29,
    gender: "female",
    email: "sarah.brown@x.dummyjson.com",
    phone: "+44 20 1234 5678",
    username: "sarahb",
    password: "sarahpass",
    birthDate: "1995-3-15",
    image: "/placeholder.svg?height=200&width=200",
    bloodGroup: "B-",
    height: 165.3,
    weight: 58.4,
    eyeColor: "Brown",
    hair: {
      color: "Blonde",
      type: "Wavy",
    },
    ip: "172.16.0.1",
    address: {
      address: "789 Maple Road",
      city: "London",
      state: "England",
      stateCode: "EN",
      postalCode: "SW1A 1AA",
      coordinates: {
        lat: 51.5074,
        lng: -0.1278,
      },
      country: "United Kingdom",
    },
    macAddress: "AA:BB:CC:DD:EE:FF",
    university: "University of Oxford",
    bank: {
      cardExpire: "09/27",
      cardNumber: "5555555555554444",
      cardType: "Mastercard",
      currency: "GBP",
      iban: "GB29NWBK60161331926819",
    },
    company: {
      department: "Human Resources",
      name: "British Enterprises Ltd.",
      title: "HR Manager",
      address: {
        address: "10 Business Square",
        city: "London",
        state: "England",
        stateCode: "EN",
        postalCode: "EC2A 1AE",
        coordinates: {
          lat: 51.5075,
          lng: -0.1279,
        },
        country: "United Kingdom",
      },
    },
    ein: "GB-123-456",
    ssn: "AB-12-34-56-C",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15",
    crypto: {
      coin: "Bitcoin",
      wallet: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
      network: "Bitcoin",
    },
    role: "user",
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Miller",
    maidenName: "Wilson",
    age: 42,
    gender: "male",
    email: "david.miller@x.dummyjson.com",
    phone: "+61 2 9876 5432",
    username: "davidm",
    password: "davidpass",
    birthDate: "1982-11-20",
    image: "/placeholder.svg?height=200&width=200",
    bloodGroup: "AB+",
    height: 188.0,
    weight: 82.5,
    eyeColor: "Hazel",
    hair: {
      color: "Brown",
      type: "Short",
    },
    ip: "10.0.0.1",
    address: {
      address: "42 Beach Boulevard",
      city: "Sydney",
      state: "New South Wales",
      stateCode: "NSW",
      postalCode: "2000",
      coordinates: {
        lat: -33.8688,
        lng: 151.2093,
      },
      country: "Australia",
    },
    macAddress: "11:22:33:44:55:66",
    university: "University of Sydney",
    bank: {
      cardExpire: "12/24",
      cardNumber: "378282246310005",
      cardType: "American Express",
      currency: "AUD",
      iban: "AU1234567890123456",
    },
    company: {
      department: "Finance",
      name: "Aussie Financial Group",
      title: "Financial Analyst",
      address: {
        address: "100 Finance Street",
        city: "Sydney",
        state: "New South Wales",
        stateCode: "NSW",
        postalCode: "2001",
        coordinates: {
          lat: -33.8689,
          lng: 151.2094,
        },
        country: "Australia",
      },
    },
    ein: "AU-987-654",
    ssn: "123-456-789",
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
    crypto: {
      coin: "Dogecoin",
      wallet: "D8gfFBxAWMNw269UaVTgNhRbEkLv3HiS4P",
      network: "Dogecoin",
    },
    role: "user",
  },
  {
    id: 5,
    firstName: "Jessica",
    lastName: "Garcia",
    maidenName: "Martinez",
    age: 31,
    gender: "female",
    email: "jessica.garcia@x.dummyjson.com",
    phone: "+52 55 1234 5678",
    username: "jessicag",
    password: "jessicapass",
    birthDate: "1993-7-8",
    image: "/placeholder.svg?height=200&width=200",
    bloodGroup: "O+",
    height: 170.2,
    weight: 65.8,
    eyeColor: "Brown",
    hair: {
      color: "Black",
      type: "Wavy",
    },
    ip: "187.45.23.10",
    address: {
      address: "567 Palm Avenue",
      city: "Mexico City",
      state: "Mexico City",
      stateCode: "CDMX",
      postalCode: "06000",
      coordinates: {
        lat: 19.4326,
        lng: -99.1332,
      },
      country: "Mexico",
    },
    macAddress: "77:88:99:AA:BB:CC",
    university: "Universidad Nacional Autónoma de México",
    bank: {
      cardExpire: "07/26",
      cardNumber: "6011111111111117",
      cardType: "Discover",
      currency: "MXN",
      iban: "MX12345678901234567890",
    },
    company: {
      department: "Sales",
      name: "Mexican Imports & Exports",
      title: "Sales Representative",
      address: {
        address: "789 Commerce Street",
        city: "Mexico City",
        state: "Mexico City",
        stateCode: "CDMX",
        postalCode: "06010",
        coordinates: {
          lat: 19.4327,
          lng: -99.1333,
        },
        country: "Mexico",
      },
    },
    ein: "MX-456-789",
    ssn: "987-65-4321",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1",
    crypto: {
      coin: "Litecoin",
      wallet: "LTC123456789abcdef123456789abcdef123",
      network: "Litecoin",
    },
    role: "moderator",
  },
];

// Generate more mock users to have at least 30
for (let i = 6; i <= 30; i++) {
  const roles = ["admin", "moderator", "user"];
  const genders = ["male", "female"];
  const departments = [
    "Engineering",
    "Marketing",
    "Sales",
    "Finance",
    "Human Resources",
    "Product",
    "Customer Support",
  ];

  mockUsers.push({
    id: i,
    firstName: `User${i}`,
    lastName: `LastName${i}`,
    maidenName: `Maiden${i}`,
    age: 25 + (i % 30),
    gender: genders[i % genders.length],
    email: `user${i}@x.dummyjson.com`,
    phone: `+1 555-${i}00-${i}999`,
    username: `user${i}`,
    password: `pass${i}`,
    birthDate: `199${i % 10}-${1 + (i % 12)}-${1 + (i % 28)}`,
    image: `/placeholder.svg?height=200&width=200`,
    bloodGroup: "A+",
    height: 160 + (i % 30),
    weight: 60 + (i % 30),
    eyeColor: "Brown",
    hair: {
      color: "Brown",
      type: "Straight",
    },
    ip: `192.168.1.${i}`,
    address: {
      address: `${i}00 Main Street`,
      city: "Anytown",
      state: "Anystate",
      stateCode: "AS",
      postalCode: `${i}0000`,
      coordinates: {
        lat: 40 + i / 100,
        lng: -70 - i / 100,
      },
      country: "United States",
    },
    macAddress: `00:1A:2B:3C:4D:${i}E`,
    university: "Any University",
    bank: {
      cardExpire: `0${i % 12}/25`,
      cardNumber: `41111111111111${i}`,
      cardType: "Visa",
      currency: "USD",
      iban: `US123456789012345678${i}`,
    },
    company: {
      department: departments[i % departments.length],
      name: `Company ${i}`,
      title: `${departments[i % departments.length]} Specialist`,
      address: {
        address: `${i}00 Business Ave`,
        city: "Business City",
        state: "Business State",
        stateCode: "BS",
        postalCode: `${i}0001`,
        coordinates: {
          lat: 41 + i / 100,
          lng: -71 - i / 100,
        },
        country: "United States",
      },
    },
    ein: `123-${i}56`,
    ssn: `123-45-${i}789`,
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
    crypto: {
      coin: "Bitcoin",
      wallet: `0x123456789abcdef123456789abcdef123456${i}`,
      network: "Ethereum (ERC20)",
    },
    role: roles[i % roles.length],
  });
}
